### ISSUE TITLE
Roadmap for first deb release

### ISSUE THREAD

**Issue by RyanWalker277** [RyanWalker277/DDeploy#1]
- [x] Fix the codeblock handling the directory search
- [x] Fix the inability of the script to create virtual environment during execution
- [x] Fix the inability of the script to activate virtual environment during execution
- [ ] Put the output and errors in different log files
- [ ] Package the script into a deb package
- [x] Add makemigrations and migrate command
- [x] Fix issues faced while creating symlink
- [x] Replace apt with apt-get 
- [x] Fix issues with installing apt packages through the script
- [ ] Adress the issue faced while installing mysqlclient package on ububtu
- [x] Replace user inputs with arguments
- [ ] Remove sourcing dependency from the script
